 1.Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [ ]:
array1 = np.random.randint(10,100,50) 
print(array1)

[52 91 17 66 52 51 39 26 91 88 50 17 23 94 39 78 47 90 22 26 71 59 93 75
 63 47 52 56 99 68 67 99 81 71 42 25 56 73 40 75 15 35 34 73 53 82 50 80
 40 77]


In [ ]:
array1[5::5] # salta de 5 en 5 empezando por el 51

array([51, 50, 78, 71, 47, 67, 25, 15, 82], dtype=int32)

2.Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [8]:
array2 = np.random.randint(1,21,30) 
print(array2)

[18 11  4 19 18  9  9  3 14 18  9 17  9  9 11  5 10  3  9 15  8  6 11  6
 16 13  1  2  2 14]


In [11]:
array2[1::2]

array([11, 19,  9,  3, 18, 17,  9,  5,  3, 15,  6,  6, 13,  2, 14],
      dtype=int32)

 3.Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [16]:
array = np.random.random_sample((4, 6)) * 100 
print(array)

[[42.4313369  58.86433269  5.41138682 46.55947254 40.28569458 59.99884283]
 [43.03356881 67.07392471 56.76785945 35.60981921 38.4164535  83.04509039]
 [50.85649416  8.415557    2.75469442 45.85116018 19.36996492 93.94888461]
 [ 3.98048086 51.83784723 21.74876984  6.40114353 57.29383326 25.818083  ]]


In [17]:
 np.round(array,2)

array([[42.43, 58.86,  5.41, 46.56, 40.29, 60.  ],
       [43.03, 67.07, 56.77, 35.61, 38.42, 83.05],
       [50.86,  8.42,  2.75, 45.85, 19.37, 93.95],
       [ 3.98, 51.84, 21.75,  6.4 , 57.29, 25.82]])

In [22]:
array=np.round( (np.random.random_sample((4, 6)) * 2),2)[-1]
print(array)

[0.24 1.14 1.17 1.55 1.07 1.28]


Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [23]:
array_tri = np.round( np.random.rand(2,3,5),1)
print(array_tri)

[[[0.7 0.9 0.6 0.1 0.3]
  [0.2 0.1 0.1 0.7 0.9]
  [0.5 0.6 0.7 0.2 0.3]]

 [[0.2 0.9 0.6 0.8 0.1]
  [0.4 0.1 0.4 0.2 0.6]
  [0.5 0.1 0.7 0.5 0. ]]]



Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [28]:
array_tri2 =np.empty((2,3,5))
print(array_tri2) # crea un array vacio 

[[[1.02955160e-311 1.02765654e-321 0.00000000e+000 0.00000000e+000
   6.23053614e-307]
  [5.02034658e+175 1.46555541e-075 1.34911873e+161 1.42555085e+160
   4.31646607e-061]
  [2.76761847e-057 8.07866617e-144 3.59751658e+252 3.96046095e+246
   1.04918621e-153]]

 [[7.69165785e+218 5.04621343e+180 1.04917822e-153 9.08366793e+223
   1.46555541e-075]
  [1.34911873e+161 1.42555085e+160 4.31646607e-061 1.04917752e-153
   1.94918966e-153]
  [3.93231563e-062 6.36601159e-062 1.14261193e-071 2.59027896e-144
   7.79952704e-143]]]


In [30]:
np.mean(array_tri2)
media=np.mean(array_tri2)

In [ ]:
np.where